stages:
  - maventry
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest

before_script:
   - export JAVA_HOME="/"


maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot-runner  # this is LINK to the shell runner on the remote-server 
  script:
    - cd backend
    - cd Final
    - mvn package -B

maven-test:
  stage: maventest
  tags:
    - springboot-runner
  script:
    - cd backend
    - cd Final
    - mvn test

autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot-runner
  script:
    - cd backend 
    - cd Final
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo


android-build: #this is another job
  image: gjandres/android-ci:latest      # this is a directive to DOCKER
  stage: androidbuild
  tags:
   - frontend         #this is LINK to the docker runner on the remote-server    
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/First/gradlew    
  script:
    - cd frontend
    - cd First
    - ./gradlew assemble

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/First/gradlew
  tags:
   - frontend
  script:
    - cd frontend
    - cd First
    - ./gradlew test
